// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // ─── Limpeza preventiva de sessão stale ──────────────────────────────────
  // MOTIVO: toda query Supabase aguarda `initializePromise` internamente.
  // Se o access_token está expirado, o Supabase tenta renovar via refresh_token.
  // No Safari/iOS, essa chamada de rede pode travar INDEFINIDAMENTE quando:
  //   • a rede está indisponível (app em segundo plano, sem sinal)
  //   • o refresh_token foi revogado pelo Google
  // Isso bloqueia TODAS as queries — produtos, categorias, pedidos, etc.
  //
  // Solução: remover a sessão stale ANTES de criar o cliente, forçando start
  // sem sessão. O usuário precisará fazer login novamente, mas o app não trava.
  if (typeof window !== "undefined") {
    const projectRef = SUPABASE_URL.match(/https?:\/\/([^.]+)\./)?.[1];
    if (projectRef) {
      const storageKey = `sb-${projectRef}-auth-token`;
      try {
        const raw = localStorage.getItem(storageKey);
        if (raw) {
          const parsed = JSON.parse(raw);
          const refreshToken: string | undefined = parsed?.refresh_token;

          if (!refreshToken) {
            // Sem refresh_token: impossível renovar a sessão → remove.
            // Não removemos com base em expires_at porque o refresh_token
            // ainda pode ser válido por dias/semanas — o Supabase renova
            // automaticamente via autoRefreshToken. Remover aqui forçaria
            // re-login a cada hora (duração padrão do access_token).
            localStorage.removeItem(storageKey);
            console.warn("[Supabase] Sessão sem refresh_token removida (evita bloqueio).");
          }
        }
      } catch {
        // Token corrompido (JSON inválido) — remover
        try {
          localStorage.removeItem(`sb-${projectRef}-auth-token`);
          console.warn("[Supabase] Token corrompido removido.");
        } catch {
          /* noop */
        }
      }
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      // ─── Timeout para chamadas de autenticação (/auth/v1/) ────────────
      // Sem esse timeout, initializePromise pode travar para sempre no Safari/iOS
      // quando a rede está indisponível durante a renovação do token.
      // Após 30s a requisição é abortada → initializePromise resolve com erro
      // → session é removida → app inicia sem sessão (em vez de travar).
      // 30s (em vez de 10s) evita falsos positivos em redes lentas — um refresh
      // de token legítimo em 3G lento leva ~15s e não deve derrubar a sessão.
      fetch: (url, options = {}) => {
        const isAuthCall = typeof url === "string" && url.includes("/auth/v1/");
        if (!isAuthCall) return fetch(url, options);

        const controller = new AbortController();
        const timeoutId = setTimeout(() => {
          controller.abort();
          console.warn("[Supabase] Auth request abortado por timeout (30s):", url);
        }, 30_000);

        return fetch(url, { ...options, signal: controller.signal }).finally(() =>
          clearTimeout(timeoutId),
        );
      },
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
