// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // ─── Versionamento e limpeza de cache ────────────────────────────────────
  // Quando APP_CACHE_VERSION mudar, dados de cache de versões antigas são
  // removidos automaticamente. O token de sessão Supabase é preservado —
  // usuário não perde o login num update normal de versão.
  //
  // Para forçar re-login em todos os usuários (ex: mudança de schema de auth),
  // incremente a versão E inclua a chave sb-* na lista de limpeza.
  const APP_CACHE_VERSION = "v1";
  const APP_CACHE_VERSION_KEY = "app_cache_version";

  if (typeof window !== "undefined") {
    try {
      const storedVersion = localStorage.getItem(APP_CACHE_VERSION_KEY);
      if (storedVersion !== APP_CACHE_VERSION) {
        if (storedVersion) {
          console.log(
            `[Cache] Versão alterada (${storedVersion} → ${APP_CACHE_VERSION}) — limpando cache antigo`,
          );
          // Remove apenas chaves de cache customizadas (não o token Supabase)
          const appCacheKeys: string[] = [];
          for (let i = 0; i < localStorage.length; i++) {
            const key = localStorage.key(i);
            if (
              key &&
              (key.startsWith("app_") || key.startsWith("query_") || key.startsWith("cache_"))
            ) {
              appCacheKeys.push(key);
            }
          }
          appCacheKeys.forEach((k) => {
            localStorage.removeItem(k);
            console.log("[Cache] cache cleared:", k);
          });
        }
        localStorage.setItem(APP_CACHE_VERSION_KEY, APP_CACHE_VERSION);
        console.log("[Cache] cache loaded — version:", APP_CACHE_VERSION);
      }
    } catch {
      /* noop — localStorage pode estar bloqueado em modo privado */
    }
  }

  // ─── Limpeza de sessão Supabase corrompida ────────────────────────────────
  // MOTIVO: se o token armazenado estiver corrompido (JSON inválido, campos
  // ausentes), o Supabase fica em loop tentando renovar indefinidamente.
  // Detectamos e removemos antes de criar o cliente para evitar esse bloqueio.
  // O INITIAL_SESSION do onAuthStateChange resolverá como null — o usuário
  // verá a tela de login em vez de um spinner infinito.
  if (typeof window !== "undefined") {
    const projectRef = SUPABASE_URL.match(/https?:\/\/([^.]+)\./)?.[1];
    if (projectRef) {
      const storageKey = `sb-${projectRef}-auth-token`;
      try {
        const raw = localStorage.getItem(storageKey);
        if (raw) {
          const parsed = JSON.parse(raw);
          // Supabase v2 armazena o token diretamente no nível raiz
          const refreshToken: string | undefined =
            parsed?.refresh_token ?? parsed?.currentSession?.refresh_token;

          if (!refreshToken) {
            // Sem refresh_token: impossível renovar → remove para evitar bloqueio
            localStorage.removeItem(storageKey);
            console.warn("[Cache] cache invalid — sessão sem refresh_token removida");
          } else {
            console.log("[Cache] cache loaded — sessão Supabase válida");
          }
        }
      } catch {
        // Token com JSON inválido — remover
        try {
          localStorage.removeItem(`sb-${projectRef}-auth-token`);
          console.warn("[Cache] cache invalid — token corrompido removido");
          console.log("[Cache] cache rebuilt — Supabase iniciará sem sessão");
        } catch {
          /* noop */
        }
      }
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      // ─── Timeout para chamadas de autenticação (/auth/v1/) ────────────
      // Sem esse timeout, initializePromise pode travar para sempre no Safari/iOS
      // quando a rede está indisponível durante a renovação do token.
      // Após 30s a requisição é abortada → initializePromise resolve com erro
      // → session é removida → app inicia sem sessão (em vez de travar).
      // 30s (em vez de 10s) evita falsos positivos em redes lentas — um refresh
      // de token legítimo em 3G lento leva ~15s e não deve derrubar a sessão.
      fetch: (url, options = {}) => {
        const isAuthCall = typeof url === "string" && url.includes("/auth/v1/");
        if (!isAuthCall) return fetch(url, options);

        const controller = new AbortController();
        const timeoutId = setTimeout(() => {
          controller.abort();
          console.warn("[Supabase] Auth request abortado por timeout (30s):", url);
        }, 30_000);

        return fetch(url, { ...options, signal: controller.signal }).finally(() =>
          clearTimeout(timeoutId),
        );
      },
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
