// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Limpa sessões Google OAuth expiradas do localStorage ANTES de criar o cliente.
  // Motivo: toda query Supabase chama getSession() internamente, que aguarda
  // initializePromise. Se há uma sessão Google expirada em localStorage, o Supabase
  // tenta renovar o token via rede — se Google OAuth não está configurado no projeto,
  // a chamada trava por 30-60s, bloqueando TODAS as queries de banco de dados.
  if (typeof window !== 'undefined') {
    const projectRef = SUPABASE_URL.match(/https?:\/\/([^.]+)\./)?.[1];
    if (projectRef) {
      const storageKey = `sb-${projectRef}-auth-token`;
      try {
        const raw = localStorage.getItem(storageKey);
        if (raw) {
          const parsed = JSON.parse(raw);
          const provider = parsed?.user?.app_metadata?.provider;
          const expiresAt: number | undefined = parsed?.expires_at;
          const isExpired = !expiresAt || expiresAt * 1000 < Date.now();
          if (provider === 'google' && isExpired) {
            localStorage.removeItem(storageKey);
            console.warn('[Supabase] Sessão Google OAuth expirada removida para evitar bloqueio de inicialização.');
          }
        }
      } catch {
        // Token corrompido (parse falhou) — remover também
        try { localStorage.removeItem(`sb-${projectRef}-auth-token`); } catch { /* noop */ }
      }
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

